services:
  english-study:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english-study-app
    ports:
      - "8501:8501"
    volumes:
      - db_volume:/app/src/db
      - st_volume:/app/src/.streamlit
    environment:
      # Configura variables de entorno aquí o usa un archivo .env
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Agrega aquí las variables de secrets.toml como variables de entorno
    restart: unless-stopped
    # acceso a GPU para PyTorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  db_volume:
  st_volume: